version: "3.8"
services:
  web:
    image: "trivia-web"
    build:
      context: "./frontend"
    ports:
      - "8090:80"
  app:
    image: "trivia-app"
    build:
      context: "./backend"
    environment:
      - DB_URL=${DB_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: "postgres:15.6-alpine"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=trivia_quiz